import 'dart:io';

import 'package:path/path.dart' as path;
import 'package:petracore_flutter_frontend_starter/petracore_flutter_frontend_starter.dart';

import '../templates/auth/auth_templates.dart';

class AuthFlowConfig {
  final String projectName;
  final String outputPath;

  // Auth features to generate
  final bool includeLogin;
  final bool includeSignup;
  final bool includeEmailVerification;
  final bool includeForgotPassword;
  final bool includePhoneVerification;
  final bool includeOtp;

  // Onboarding screens
  final bool includeSplashScreen;
  final bool includeWelcomeScreen;
  final bool includeGetStartedScreen;

  // Additional options
  final bool includeSocialAuth;
  final bool includeDeviceToken;

  AuthFlowConfig({
    required this.projectName,
    required this.outputPath,
    this.includeLogin = true,
    this.includeSignup = true,
    this.includeEmailVerification = true,
    this.includeForgotPassword = true,
    this.includePhoneVerification = false,
    this.includeOtp = false,
    this.includeSplashScreen = true,
    this.includeWelcomeScreen = true,
    this.includeGetStartedScreen = true,
    this.includeSocialAuth = false,
    this.includeDeviceToken = false,
  });

  String get className => projectName
      .split('_')
      .map((word) => word[0].toUpperCase() + word.substring(1))
      .join();
}

class AuthFlowGenerator {
  final AuthFlowConfig config;
  late final AuthTemplates templates;

  AuthFlowGenerator(this.config) {
    // Create a minimal ProjectConfig for the templates
    final projectConfig = ProjectConfig(
      projectName: config.projectName,
      organization: 'com.example',
      description: 'Generated by PetraCore CLI',
      projectPath: config.outputPath,
    );
    templates = AuthTemplates(projectConfig);
  }

  Future<void> generate() async {
    Logger.step('Creating auth feature directory structure...');
    await _createDirectoryStructure();

    Logger.step('Generating shared type definitions...');
    await _generateSharedTypes();

    Logger.step('Generating auth models...');
    await _generateAuthModels();

    Logger.step('Generating auth DTOs...');
    await _generateAuthDtos();

    Logger.step('Generating auth enums...');
    await _generateAuthEnums();

    Logger.step('Generating auth repository and service...');
    await _generateRepositoryLayer();

    Logger.step('Generating auth use cases...');
    await _generateUseCases();

    Logger.step('Generating auth BLoC...');
    await _generateAuthBloc();

    if (config.includeSplashScreen ||
        config.includeWelcomeScreen ||
        config.includeGetStartedScreen) {
      Logger.step('Generating onboarding screens...');
      await _generateOnboardingScreens();
    }

    if (config.includeLogin || config.includeSignup) {
      Logger.step('Generating auth screens...');
      await _generateAuthScreens();

      Logger.step('Generating auth controllers...');
      await _generateAuthControllers();
    }

    Logger.step('Generating index files...');
    await _generateIndexFiles();

    Logger.verbose('Auth flow generation completed');
  }

  Future<void> _createDirectoryStructure() async {
    final dirs = [
      config.outputPath,
      path.join(config.outputPath, 'lib'),
      path.join(config.outputPath, 'lib', 'features'),
      path.join(config.outputPath, 'lib', 'features', 'auth'),
      path.join(config.outputPath, 'lib', 'features', 'auth', 'data'),
      path.join(config.outputPath, 'lib', 'features', 'auth', 'data', 'models'),
      path.join(config.outputPath, 'lib', 'features', 'auth', 'data', 'remote'),
      path.join(config.outputPath, 'lib', 'features', 'auth', 'data', 'remote',
          'dtos'),
      path.join(
          config.outputPath, 'lib', 'features', 'auth', 'data', 'use_case'),
      path.join(config.outputPath, 'lib', 'features', 'auth', 'data', 'enums'),
      path.join(config.outputPath, 'lib', 'features', 'auth', 'presentation'),
      path.join(config.outputPath, 'lib', 'features', 'auth', 'presentation',
          'controllers'),
      path.join(config.outputPath, 'lib', 'features', 'auth', 'presentation',
          'controllers', 'blocs'),
      path.join(config.outputPath, 'lib', 'features', 'auth', 'presentation',
          'controllers', 'blocs', 'auth_bloc'),
      path.join(config.outputPath, 'lib', 'features', 'auth', 'presentation',
          'screens'),
      path.join(config.outputPath, 'lib', 'features', 'auth', 'presentation',
          'screens', 'login'),
      path.join(config.outputPath, 'lib', 'features', 'auth', 'presentation',
          'screens', 'signup'),
      path.join(config.outputPath, 'lib', 'features', 'auth', 'presentation',
          'helpers'),
      path.join(config.outputPath, 'lib', 'features', 'shared'),
      path.join(config.outputPath, 'lib', 'features', 'shared', 'data'),
    ];

    for (final dir in dirs) {
      await Directory(dir).create(recursive: true);
      Logger.verbose(
          'Created directory: ${path.relative(dir, from: config.outputPath)}');
    }
  }

  Future<void> _generateSharedTypes() async {
    final filePath = path.join(config.outputPath, 'lib', 'features', 'shared',
        'data', 'type_def.dart');
    await FileUtils.writeFile(filePath, templates.typeDefinitions);
    Logger.verbose(
        'Generated: ${path.relative(filePath, from: config.outputPath)}');
  }

  Future<void> _generateAuthModels() async {
    final files = {
      'lib/features/auth/data/models/user_model.dart': templates.userModel,
      'lib/features/auth/data/models/models.dart': templates.authModelsIndex,
    };

    for (final entry in files.entries) {
      final filePath = path.join(config.outputPath, entry.key);
      await FileUtils.writeFile(filePath, entry.value);
      Logger.verbose('Generated: ${entry.key}');
    }
  }

  Future<void> _generateAuthDtos() async {
    final files = <String, String>{
      'lib/features/auth/data/remote/dtos/dtos.dart': templates.authDtosIndex,
    };

    // Always include login and signup DTOs
    if (config.includeLogin) {
      files['lib/features/auth/data/remote/dtos/login_dto.dart'] =
          templates.loginDto;
    }
    if (config.includeSignup) {
      files['lib/features/auth/data/remote/dtos/sign_up_dto.dart'] =
          templates.signUpDto;
    }

    // Conditional DTOs based on features
    if (config.includeEmailVerification || config.includePhoneVerification) {
      files['lib/features/auth/data/remote/dtos/verify_dto.dart'] =
          templates.verifyDto;
      files['lib/features/auth/data/remote/dtos/check_user_dto.dart'] =
          templates.checkUserDto;
    }

    if (config.includeOtp) {
      files['lib/features/auth/data/remote/dtos/request_otp_dto.dart'] =
          templates.requestOtpDto;
    }

    if (config.includeForgotPassword) {
      files['lib/features/auth/data/remote/dtos/reset_password_dto.dart'] =
          templates.resetPasswordDto;
    }

    for (final entry in files.entries) {
      final filePath = path.join(config.outputPath, entry.key);
      await FileUtils.writeFile(filePath, entry.value);
      Logger.verbose('Generated: ${entry.key}');
    }
  }

  Future<void> _generateAuthEnums() async {
    final filePath = path.join(config.outputPath, 'lib', 'features', 'auth',
        'data', 'enums', 'auth_enums.dart');
    await FileUtils.writeFile(filePath, templates.authEnums);
    Logger.verbose(
        'Generated: ${path.relative(filePath, from: config.outputPath)}');
  }

  Future<void> _generateRepositoryLayer() async {
    final files = {
      'lib/features/auth/data/remote/auth_repository.dart':
          templates.authRepository,
      'lib/features/auth/data/remote/auth_service.dart': templates.authService,
    };

    for (final entry in files.entries) {
      final filePath = path.join(config.outputPath, entry.key);
      await FileUtils.writeFile(filePath, entry.value);
      Logger.verbose('Generated: ${entry.key}');
    }
  }

  Future<void> _generateUseCases() async {
    final filePath = path.join(config.outputPath, 'lib', 'features', 'auth',
        'data', 'use_case', 'auth_use_cases.dart');
    await FileUtils.writeFile(filePath, templates.authUseCases);
    Logger.verbose(
        'Generated: ${path.relative(filePath, from: config.outputPath)}');
  }

  Future<void> _generateAuthBloc() async {
    final files = {
      'lib/features/auth/presentation/controllers/blocs/auth_bloc/auth_bloc.dart':
          templates.authBloc,
      'lib/features/auth/presentation/controllers/blocs/auth_bloc/auth_event.dart':
          templates.authBlocEvents,
      'lib/features/auth/presentation/controllers/blocs/auth_bloc/auth_state.dart':
          templates.authBlocStates,
    };

    for (final entry in files.entries) {
      final filePath = path.join(config.outputPath, entry.key);
      await FileUtils.writeFile(filePath, entry.value);
      Logger.verbose('Generated: ${entry.key}');
    }
  }

  Future<void> _generateAuthScreens() async {
    final files = <String, String>{};

    if (config.includeLogin) {
      files['lib/features/auth/presentation/screens/login/login_screen.dart'] =
          templates.loginScreen;
    }

    if (config.includeSignup) {
      files['lib/features/auth/presentation/screens/signup/signup_screen.dart'] =
          templates.signupScreen;
    }

    if (files.isNotEmpty) {
      files['lib/features/auth/presentation/screens/screens.dart'] =
          templates.authScreensIndex;
    }

    for (final entry in files.entries) {
      final filePath = path.join(config.outputPath, entry.key);
      await FileUtils.writeFile(filePath, entry.value);
      Logger.verbose('Generated: ${entry.key}');
    }
  }

  Future<void> _generateAuthControllers() async {
    final files = <String, String>{};

    if (config.includeLogin) {
      files['lib/features/auth/presentation/helpers/login_controller.dart'] =
          templates.loginController;
    }

    if (config.includeSignup) {
      files['lib/features/auth/presentation/helpers/signup_controller.dart'] =
          templates.signupController;
    }

    if (config.includeGetStartedScreen) {
      files['lib/features/auth/presentation/helpers/get_started_controller.dart'] =
          templates.getStartedController;
    }

    if (files.isNotEmpty) {
      files['lib/features/auth/presentation/helpers/helpers.dart'] =
          templates.authHelpersIndex;
    }

    for (final entry in files.entries) {
      final filePath = path.join(config.outputPath, entry.key);
      await FileUtils.writeFile(filePath, entry.value);
      Logger.verbose('Generated: ${entry.key}');
    }
  }

  Future<void> _generateOnboardingScreens() async {
    final files = <String, String>{};
    final dirs = <String>[];

    if (config.includeSplashScreen) {
      dirs.add(path.join(config.outputPath, 'lib', 'features', 'auth',
          'presentation', 'screens', 'onboarding'));
      files['lib/features/auth/presentation/screens/onboarding/splash_screen.dart'] =
          templates.splashScreen;
    }

    if (config.includeWelcomeScreen) {
      dirs.add(path.join(config.outputPath, 'lib', 'features', 'auth',
          'presentation', 'screens', 'onboarding'));
      files['lib/features/auth/presentation/screens/onboarding/welcome_screen.dart'] =
          templates.welcomeScreen;
    }

    if (config.includeGetStartedScreen) {
      dirs.add(path.join(config.outputPath, 'lib', 'features', 'auth',
          'presentation', 'screens', 'onboarding'));
      files['lib/features/auth/presentation/screens/onboarding/get_started_screen.dart'] =
          templates.getStartedScreen;
    }

    // Create onboarding directory if needed
    for (final dir in dirs.toSet()) {
      await Directory(dir).create(recursive: true);
    }

    for (final entry in files.entries) {
      final filePath = path.join(config.outputPath, entry.key);
      await FileUtils.writeFile(filePath, entry.value);
      Logger.verbose('Generated: ${entry.key}');
    }
  }

  Future<void> _generateIndexFiles() async {
    final files = {
      'lib/features/auth/auth_index.dart': templates.authIndex,
      'lib/features/auth/data/data.dart': templates.authDataIndex,
      'lib/features/auth/presentation/presentation.dart':
          templates.authPresentationIndex,
      'lib/features/auth/presentation/controllers/controllers.dart':
          templates.authControllersIndex,
    };

    for (final entry in files.entries) {
      final filePath = path.join(config.outputPath, entry.key);
      await FileUtils.writeFile(filePath, entry.value);
      Logger.verbose('Generated: ${entry.key}');
    }
  }

  /// Interactive method to collect user preferences
  static Future<AuthFlowConfig> createInteractiveConfig(
      String projectPath) async {
    Logger.header('🔐 Auth Flow Generator');
    Logger.info('Let\'s set up authentication for your Flutter project!\n');

    // Get project name from current directory or user input
    final projectName = path.basename(projectPath);
    Logger.info('Project: $projectName');
    Logger.info('Location: $projectPath\n');

    // Ask about onboarding screens
    Logger.info('🎬 Onboarding Screens:');
    final includeSplashScreen =
        _askYesNo('Include Splash Screen?', defaultValue: true);
    final includeWelcomeScreen =
        _askYesNo('Include Welcome Screen?', defaultValue: true);
    final includeGetStartedScreen = _askYesNo(
        'Include Get Started Screen (email entry)?',
        defaultValue: true);

    // Ask about core auth features
    Logger.info('\n🔐 Core Authentication:');
    final includeLogin =
        _askYesNo('Include Login functionality?', defaultValue: true);
    final includeSignup =
        _askYesNo('Include Signup functionality?', defaultValue: true);

    // Ask about additional features
    Logger.info('\n📧 Additional Authentication Features:');
    final includeEmailVerification =
        _askYesNo('Include Email Verification?', defaultValue: false);
    final includeForgotPassword =
        _askYesNo('Include Forgot Password?', defaultValue: false);
    final includePhoneVerification =
        _askYesNo('Include Phone Verification?', defaultValue: false);
    final includeOtp = _askYesNo(
        'Include OTP (One-Time Password) functionality?',
        defaultValue: false);

    // Ask about advanced features
    Logger.info('\n🔧 Advanced Features:');
    final includeSocialAuth = _askYesNo(
        'Include Social Authentication placeholders?',
        defaultValue: false);
    final includeDeviceToken = _askYesNo(
        'Include Device Token support (for push notifications)?',
        defaultValue: false);

    return AuthFlowConfig(
      projectName: projectName,
      outputPath: projectPath,
      includeLogin: includeLogin,
      includeSignup: includeSignup,
      includeEmailVerification: includeEmailVerification,
      includeForgotPassword: includeForgotPassword,
      includePhoneVerification: includePhoneVerification,
      includeOtp: includeOtp,
      includeSplashScreen: includeSplashScreen,
      includeWelcomeScreen: includeWelcomeScreen,
      includeGetStartedScreen: includeGetStartedScreen,
      includeSocialAuth: includeSocialAuth,
      includeDeviceToken: includeDeviceToken,
    );
  }

  static bool _askYesNo(String question, {bool defaultValue = false}) {
    final defaultText = defaultValue ? 'Y/n' : 'y/N';
    stdout.write('$question ($defaultText): ');
    final input = stdin.readLineSync()?.toLowerCase().trim() ?? '';

    if (input.isEmpty) return defaultValue;
    return input == 'y' || input == 'yes';
  }
}
